-- ========================
-- DROP TABLES (en orden inverso para evitar conflictos de llaves foraneas)
-- ========================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE mascota_evento CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE evento_participante CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE mascota CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE participante CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE evento CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tipo_mascota CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comuna CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE region CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ========================
-- Tablas de la base de datos
-- ========================

CREATE TABLE region (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE comuna (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    region_id NUMBER NOT NULL,
    CONSTRAINT fk_comuna_region FOREIGN KEY (region_id) REFERENCES region(id),
    CONSTRAINT uq_comuna_nombre_region UNIQUE (nombre, region_id)
);

CREATE TABLE tipo_mascota (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_tipo_mascota_nombre UNIQUE (nombre)
);

CREATE TABLE participante (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL
);

CREATE TABLE evento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(500),
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    ubicacion VARCHAR2(200),
    comuna_id NUMBER NOT NULL,
    CONSTRAINT fk_evento_comuna FOREIGN KEY (comuna_id) REFERENCES comuna(id)
);

CREATE TABLE mascota (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo_mascota_id NUMBER NOT NULL,
    participante_id NUMBER NOT NULL,
    CONSTRAINT fk_mascota_tipo FOREIGN KEY (tipo_mascota_id) REFERENCES tipo_mascota(id),
    CONSTRAINT fk_mascota_participante FOREIGN KEY (participante_id) REFERENCES participante(id)
);

CREATE TABLE evento_participante (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id NUMBER NOT NULL,
    participante_id NUMBER NOT NULL,
    CONSTRAINT fk_ep_evento FOREIGN KEY (evento_id) REFERENCES evento(id),
    CONSTRAINT fk_ep_participante FOREIGN KEY (participante_id) REFERENCES participante(id)
);


CREATE TABLE mascota_evento (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     mascota_id NUMBER NOT NULL,
     evento_participante_id NUMBER NOT NULL,
     CONSTRAINT fk_me_mascota FOREIGN KEY (mascota_id) REFERENCES mascota(id),
     CONSTRAINT fk_me_eventopart FOREIGN KEY (evento_participante_id) REFERENCES evento_participante(id)
);

INSERT INTO region (nombre) VALUES ('Región Metropolitana');
INSERT INTO region (nombre) VALUES ('Valparaíso');
INSERT INTO region (nombre) VALUES ('Biobío');
INSERT INTO comuna (nombre, region_id) VALUES ('Santiago', 1);
INSERT INTO comuna (nombre, region_id) VALUES ('Puente Alto', 1);
INSERT INTO comuna (nombre, region_id) VALUES ('Maipú', 1);
INSERT INTO comuna (nombre, region_id) VALUES ('Viña del Mar', 2);
INSERT INTO comuna (nombre, region_id) VALUES ('Valparaíso', 2);
INSERT INTO comuna (nombre, region_id) VALUES ('Quilpué', 2);
INSERT INTO comuna (nombre, region_id) VALUES ('Concepción', 3);
INSERT INTO comuna (nombre, region_id) VALUES ('Talcahuano', 3);
INSERT INTO comuna (nombre, region_id) VALUES ('Los Ángeles', 3);
INSERT INTO tipo_mascota (nombre) VALUES ('Perro');
INSERT INTO tipo_mascota (nombre) VALUES ('Gato');
INSERT INTO tipo_mascota (nombre) VALUES ('Conejo');
INSERT INTO participante (nombre, email) VALUES ('Juan Pérez', 'juan.perez@example.com');
INSERT INTO participante (nombre, email) VALUES ('Ana López', 'ana.lopez@example.com');
INSERT INTO participante (nombre, email) VALUES ('Carlos Díaz', 'carlos.diaz@example.com');
INSERT INTO evento (nombre, descripcion, fecha_inicio, fecha_fin, ubicacion, comuna_id) VALUES ('Expo Mascotas', 'Evento para amantes de mascotas', TO_TIMESTAMP('2025-05-06 02:30:33', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-06 06:30:33', 'YYYY-MM-DD HH24:MI:SS'), 'Parque OHiggins', 1);
INSERT INTO evento (nombre, descripcion, fecha_inicio, fecha_fin, ubicacion, comuna_id) VALUES ('Feria Animal', 'Adopciones y concursos', TO_TIMESTAMP('2025-05-07 02:30:33', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-07 06:30:33', 'YYYY-MM-DD HH24:MI:SS'), 'Plaza de Armas', 2);
INSERT INTO evento (nombre, descripcion, fecha_inicio, fecha_fin, ubicacion, comuna_id) VALUES ('Concurso de Obediencia', 'Competencia de mascotas entrenadas', TO_TIMESTAMP('2025-05-08 02:30:33', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-05-08 06:30:33', 'YYYY-MM-DD HH24:MI:SS'), 'Estadio Nacional', 3);
INSERT INTO mascota (nombre, tipo_mascota_id, participante_id) VALUES ('Firulais', 1, 1);
INSERT INTO mascota (nombre, tipo_mascota_id, participante_id) VALUES ('Michi', 2, 2);
INSERT INTO mascota (nombre, tipo_mascota_id, participante_id) VALUES ('Bunny', 3, 3);
INSERT INTO evento_participante (evento_id, participante_id) VALUES (1, 1);
INSERT INTO evento_participante (evento_id, participante_id) VALUES (2, 2);
INSERT INTO evento_participante (evento_id, participante_id) VALUES (3, 3);
INSERT INTO mascota_evento (mascota_id, evento_participante_id) VALUES (1, 1);
INSERT INTO mascota_evento (mascota_id, evento_participante_id) VALUES (2, 2);
INSERT INTO mascota_evento (mascota_id, evento_participante_id) VALUES (3, 3);

commit;