-- ========================
-- DROP TABLES (en orden inverso para evitar conflictos de llaves foraneas)
-- ========================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE mascota_evento CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE evento_participante CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE mascota CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE participante CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE evento CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tipo_mascota CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comuna CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE region CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ========================
-- Tablas de la base de datos
-- ========================

CREATE TABLE region (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE comuna (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    region_id NUMBER NOT NULL,
    CONSTRAINT fk_comuna_region FOREIGN KEY (region_id) REFERENCES region(id),
    CONSTRAINT uq_comuna_nombre_region UNIQUE (nombre, region_id)
);

CREATE TABLE tipo_mascota (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT uq_tipo_mascota_nombre UNIQUE (nombre)
);

CREATE TABLE participante (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL
);

CREATE TABLE evento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(500),
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    ubicacion VARCHAR2(200),
    comuna_id NUMBER NOT NULL,
    CONSTRAINT fk_evento_comuna FOREIGN KEY (comuna_id) REFERENCES comuna(id)
);

CREATE TABLE mascota (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo_mascota_id NUMBER NOT NULL,
    participante_id NUMBER NOT NULL,
    CONSTRAINT fk_mascota_tipo FOREIGN KEY (tipo_mascota_id) REFERENCES tipo_mascota(id),
    CONSTRAINT fk_mascota_participante FOREIGN KEY (participante_id) REFERENCES participante(id)
);

CREATE TABLE evento_participante (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id NUMBER NOT NULL,
    participante_id NUMBER NOT NULL,
    CONSTRAINT fk_ep_evento FOREIGN KEY (evento_id) REFERENCES evento(id),
    CONSTRAINT fk_ep_participante FOREIGN KEY (participante_id) REFERENCES participante(id)
);


CREATE TABLE mascota_evento (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     mascota_id NUMBER NOT NULL,
     evento_participante_id NUMBER NOT NULL,
     CONSTRAINT fk_me_mascota FOREIGN KEY (mascota_id) REFERENCES mascota(id),
     CONSTRAINT fk_me_eventopart FOREIGN KEY (evento_participante_id) REFERENCES evento_participante(id)
);